### ISSUE TITLE
Error: "TypeError: result.setExpression is not a function"

### ISSUE THREAD

**Issue by GiovanniFerrara** [buz-zard/netlify-cms-widget-inline-select#11]
### Description
After installing and registering the widget I got the following error:

```
TypeError: result.setExpression is not a function
    at Parser.evaluateExpression (C:\Users\Giovanni\Desktop\orlando\node_modules\gatsby-plugin-netlify-cms\node_modules\webpack\lib\Parser.js:1987:14)
    at hooks.evaluate.for.tap.expr (C:\Users\Giovanni\Desktop\orlando\node_modules\gatsby-plugin-netlify-cms\node_modules\webpack\lib\Parser.js:189:18)
    at SyncBailHook.eval [as call] (eval at create (C:\Users\Giovanni\Desktop\orlando\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:16)
    at Parser.evaluateExpression (C:\Users\Giovanni\Desktop\orlando\node_modules\gatsby-plugin-netlify-cms\node_modules\webpack\lib\Parser.js:1984:25)
    at Parser.getRenameIdentifier (C:\Users\Giovanni\Desktop\orlando\node_modules\gatsby-plugin-netlify-cms\node_modules\webpack\lib\Parser.js:823:23)
    at Parser.walkVariableDeclaration (C:\Users\Giovanni\Desktop\orlando\node_modules\gatsby-plugin-netlify-cms\node_modules\webpack\lib\Parser.js:1364:31)
    at Parser.walkStatement (C:\Users\Giovanni\Desktop\orlando\node_modules\gatsby-plugin-netlify-cms\node_modules\webpack\lib\Parser.js:979:10)
    at Parser.walkStatements (C:\Users\Giovanni\Desktop\orlando\node_modules\gatsby-plugin-netlify-cms\node_modules\webpack\lib\Parser.js:864:9)
    at Parser.parse (C:\Users\Giovanni\Desktop\orlando\node_modules\gatsby-plugin-netlify-cms\node_modules\webpack\lib\Parser.js:2123:9)
    at doBuild.err (C:\Users\Giovanni\Desktop\orlando\node_modules\gatsby-plugin-netlify-cms\node_modules\webpack\lib\NormalModule.js:460:32)
    at runLoaders (C:\Users\Giovanni\Desktop\orlando\node_modules\gatsby-plugin-netlify-cms\node_modules\webpack\lib\NormalModule.js:342:12)
    at C:\Users\Giovanni\Desktop\orlando\node_modules\loader-runner\lib\LoaderRunner.js:370:3
    at iterateNormalLoaders (C:\Users\Giovanni\Desktop\orlando\node_modules\loader-runner\lib\LoaderRunner.js:211:10)
    at Array.<anonymous> (C:\Users\Giovanni\Desktop\orlando\node_modules\loader-runner\lib\LoaderRunner.js:202:4)
    at Storage.finished (C:\Users\Giovanni\Desktop\orlando\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:43:16)
    at provider (C:\Users\Giovanni\Desktop\orlando\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:79:9)
```

### Steps to reproduce

Install this from my repo and install the package "netlify-cms-widget-inline-select"

https://github.com/GiovanniFerrara/alessandrorlando.it

### Environment

```
System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Yarn: 1.9.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: 2.0.111 => 2.0.111
    gatsby-image: 2.0.29 => 2.0.29
    gatsby-link: 2.0.10 => 2.0.10
    gatsby-plugin-catch-links: 2.0.10 => 2.0.10
    gatsby-plugin-feed: 2.0.13 => 2.0.13
    gatsby-plugin-google-analytics: 2.0.13 => 2.0.13
    gatsby-plugin-manifest: 2.0.17 => 2.0.17
    gatsby-plugin-netlify: 2.0.8 => 2.0.8
    gatsby-plugin-netlify-cms: 3.0.0 => 3.0.0
    gatsby-plugin-nprogress: 2.0.8 => 2.0.8
    gatsby-plugin-offline: 2.0.22 => 2.0.22
    gatsby-plugin-preact: 2.0.9 => 2.0.9
    gatsby-plugin-react-helmet: 3.0.6 => 3.0.6
    gatsby-plugin-react-next: 2.0.1-13 => 2.0.1-13
    gatsby-plugin-sass: ^2.0.0-rc.2 => 2.0.0-rc.2
    gatsby-plugin-sharp: 2.0.20 => 2.0.20
    gatsby-plugin-sitemap: 2.0.5 => 2.0.5
    gatsby-plugin-twitter: 2.0.9 => 2.0.9
    gatsby-remark-copy-linked-files: 2.0.9 => 2.0.9
    gatsby-remark-images: 3.0.3 => 3.0.3
    gatsby-remark-prismjs: 3.2.4 => 3.2.4
    gatsby-remark-responsive-iframe: 2.0.9 => 2.0.9
    gatsby-remark-smartypants: 2.0.8 => 2.0.8
    gatsby-source-filesystem: 2.0.20 => 2.0.20
    gatsby-transformer-remark: 2.2.3 => 2.2.3
    gatsby-transformer-sharp: 2.1.13 => 2.1.13

```

I don't need a lot to use this package, but I hope that this helps you to verify if there are some errors.

**Comment by GiovanniFerrara** [comment]
Sorry, I realized that was a problem with the Netlify CMS plugin and Webpack. But I still haven't fixed.
